# jpa配置 数据源配置
spring:
  datasource:
    url: ${base.mysql.url}/taroco-oauth2?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: taroco@1234
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      pool-name: Taroco-OAuth2-HikariCP
  #redis配置
  redis:
    host: ${base.redis.host}
    port: ${base.redis.port}
    password: ${base.redis.password}
    database: 0
  freemarker:
    allow-request-override: false
    allow-session-override: false
    cache: true
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    enabled: true
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: true
    prefer-file-system-access: true
    suffix: .ftl
    template-loader-path: classpath:/templates/

# oauth2 配置
taroco:
  oauth2:
    key-store:
      location: classpath:taroco.jks
      secret: taroco!@#$
      alias: taroco
    url-permit-all:
      - /actuator/**
      - /authentication/**
      - /**/*.css
      - /**/*.jpg
      - /**/*.png
      - /**/*.woff2
      - /**/*.js